services:
  postgres:
    container_name: local_db_board_jira
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresdocker
      POSTGRES_DB: db_board_jira
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres